# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Capstone_CafeBronco' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Capstone_CafeBronco

  target 'Capstone_CafeBroncoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Capstone_CafeBroncoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'EstimoteSDK'


end
